import OrderedCollections

public protocol ModelVisitor<State> {
    associatedtype State
    mutating func visit<T>(path: KeyPath<State, T>)
    mutating func visit<T>(path: WritableKeyPath<State, T>)
    mutating func visit<T: Model>(path: WritableKeyPath<State, T>)
    mutating func visit<T: ModelContainer>(path: WritableKeyPath<State, T>)
    /// Called for plain-value properties that carry a `PropertyVisibility` annotation.
    /// The default implementation delegates to `visit(path:)`, preserving backward compatibility
    /// for all existing `ModelVisitor` conformers that have no need for visibility information.
    mutating func visit<T>(path: WritableKeyPath<State, T>, visibility: PropertyVisibility)
}

public extension ModelVisitor {
    mutating func visit<T>(path: KeyPath<State, T>) { }
    mutating func visit<T>(path: WritableKeyPath<State, T>) { }
    mutating func visit<T>(path: WritableKeyPath<State, T>, visibility: PropertyVisibility) {
        visit(path: path)
    }
}

public extension ModelVisitor where State: Model {
    /// Default implementation for `_State`-level paths: composes via `_modelStateKeyPath`
    /// and delegates to the existing `visit(path:)` overloads. This preserves backward
    /// compatibility — existing `ModelVisitor` implementations that only implement
    /// `visit(path:)` continue to work unchanged when the macro emits `visitStatically(statePath:)`.
    mutating func visit<T>(statePath: WritableKeyPath<State._ModelState, T>) {
        visit(path: State._modelStateKeyPath.appending(path: statePath))
    }
    mutating func visit<T: Model>(statePath: WritableKeyPath<State._ModelState, T>) {
        visit(path: State._modelStateKeyPath.appending(path: statePath) as WritableKeyPath<State, T>)
    }
    mutating func visit<T: ModelContainer>(statePath: WritableKeyPath<State._ModelState, T>) {
        visit(path: State._modelStateKeyPath.appending(path: statePath) as WritableKeyPath<State, T>)
    }
    mutating func visit<T>(statePath: WritableKeyPath<State._ModelState, T>, visibility: PropertyVisibility) {
        visit(path: State._modelStateKeyPath.appending(path: statePath), visibility: visibility)
    }
}

/// A non-parameterized protocol for visitors that need witness-table dispatch for
/// `_ModelState`-level paths (paths into the `_State` struct generated by `@Model`).
///
/// Unlike the extension methods on `ModelVisitor where State: Model`, the requirements here
/// appear in the witness table. `ContainerVisitor` detects conformance at runtime via
/// `modelVisitor as? any _ModelStateVisitor` (a non-parameterized existential, compatible
/// with macOS 11+) and dispatches through the witness table — without requiring changes to
/// the macro-generated `visit(with:)` signature or adding conditional conformances to every
/// `ModelVisitor` conformer.
///
/// Requirements use a generic `<M: Model, T>` pair plus a `forState: M.Type` discriminant so
/// the concrete conformer can recover the `M`-specific path type via `unsafeBitCast` (safe
/// because `ContainerVisitor` always passes `V.State.self` and `V.State == M`).
///
/// Default implementations are no-ops; conformers override only what they need.
protocol _ModelStateVisitor {
    mutating func _visitStatePath<M: Model, T>(
        _ statePath: WritableKeyPath<M._ModelState, T>,
        forState: M.Type
    )
    mutating func _visitStatePath<M: Model, T>(
        _ statePath: WritableKeyPath<M._ModelState, T>,
        forState: M.Type,
        visibility: PropertyVisibility
    )
}

extension _ModelStateVisitor {
    mutating func _visitStatePath<M: Model, T>(_ statePath: WritableKeyPath<M._ModelState, T>, forState: M.Type) { }
    mutating func _visitStatePath<M: Model, T>(_ statePath: WritableKeyPath<M._ModelState, T>, forState: M.Type, visibility: PropertyVisibility) { }
}

protocol ModelTransformer {
    func transform<M: Model>(_ model: inout M)
}

struct ModelTransformerVisitor<Root, Child, Transformer: ModelTransformer>: ModelVisitor {
    var root: Root
    let path: WritableKeyPath<Root, Child>
    let transformer: Transformer

    mutating func visit<T: Model>(path: WritableKeyPath<Child, T>) {
        let fullPath = self.path.appending(path: path)
        transformer.transform(&root[keyPath: fullPath])

        var visitor = ModelTransformerVisitor<Root, T, Transformer>(root: root, path: fullPath, transformer: transformer)
        root[keyPath: fullPath].visit(with: &visitor, includeSelf: false)
        root = visitor.root
    }

    mutating func visit<T: ModelContainer>(path: WritableKeyPath<Child, T>) {
        let fullPath = self.path.appending(path: path)
        var visitor = ModelTransformerVisitor<Root, T, Transformer>(root: root, path: fullPath, transformer: transformer)
        root[keyPath: fullPath].visit(with: &visitor, includeSelf: false)
        root = visitor.root
    }
}

protocol ValueReducer {
    associatedtype Value
    static func reduce<M: Model>(value: inout Value, model: M) -> Void
}

struct ReduceValueVisitor<Root, Child, Reducer: ValueReducer>: ModelVisitor {
    let root: Root
    let path: WritableKeyPath<Root, Child>
    let reducer: Reducer.Type
    var value: Reducer.Value

    mutating func visit<T: Model>(path: WritableKeyPath<Child, T>) {
        let fullPath = self.path.appending(path: path)
        reducer.reduce(value: &value, model: root[keyPath: fullPath])

        var visitor = ReduceValueVisitor<Root, T, Reducer>(root: root, path: fullPath, reducer: reducer, value: value)
        root[keyPath: fullPath].visit(with: &visitor, includeSelf: false)
        value = visitor.value
    }

    mutating func visit<T: ModelContainer>(path: WritableKeyPath<Child, T>) {
        let fullPath = self.path.appending(path: path)
        var visitor = ReduceValueVisitor<Root, T, Reducer>(root: root, path: fullPath, reducer: reducer, value: value)
        root[keyPath: fullPath].visit(with: &visitor, includeSelf: false)
        value = visitor.value
    }
}

struct AnchorVisitor<M: Model, Container: ModelContainer, Value: ModelContainer>: ModelVisitor {
    var value: Value
    var didAttemptToReplaceWithAnchoredModel = false
    let context: Context<M>
    let containerPath: WritableKeyPath<M, Container>
    let elementPath: WritableKeyPath<Container, Value>

    init(value: Value, context: Context<M>, containerPath: WritableKeyPath<M, Container>, elementPath: WritableKeyPath<Container, Value>) {
        self.value = value
        self.context = context
        self.containerPath = containerPath
        self.elementPath = elementPath
    }

    mutating func visit<T: Model>(path: WritableKeyPath<Value, T>) {
        let childModel = value[keyPath: path]
        
        let isSelf = path == \Value.self && containerPath == \M.self && elementPath == \Container.self
        let modelElementPath = elementPath.appending(path: path)

        // For child models: bail if destructed/frozen (they were removed, don't re-anchor them).
        // For the top-level model being anchored (isSelf): allow even if destructed — this is the
        // re-anchoring case (e.g. undo restoring a deleted item, or static testValue across tests).
        if !isSelf && childModel.lifetime.isDestructedOrFrozenCopy {
            threadLocals.didReplaceModelWithDestructedOrFrozenCopy()
            return
        }

        // Lazy context: during initial anchor setup (context.reference.context == nil, i.e. before
        // setContext is called in Context.init), collection elements can be registered lazily when
        // the .lazyChildContexts option is set. Their context is created on demand (first write,
        // node use, etc.) via materializeLazyContext().
        //
        // Post-anchor updates (e.g. parent.children.append(...)) always use the eager path because
        // context.reference.context is non-nil by then — the newly added element needs its context
        // immediately so that onActivate() fires and the element participates in the hierarchy.
        //
        // Direct single-model children (e.g. `var child: Child`) are always eager regardless —
        // the MutableCollection check excludes them.
        if !isSelf && context.options.contains(.lazyChildContexts) && (value is any MutableCollection) && context.reference.context == nil && childModel.modelContext.reference?.context == nil {
            context.registerLazyChild(containerPath: containerPath, elementPath: modelElementPath, childModel: childModel)
            return
        }

        // Skip children that are still lazily pending (have a creator but no context yet).
        // This prevents the second withContextAdded traversal in returningAnchor (and updateContext
        // re-traversals) from prematurely triggering childContext() → materializeLazyContext(),
        // which would fire onActivate() before the parent's onActivate() runs.
        if !isSelf, let childRef = childModel.modelContext.reference, childRef.hasLazyContextCreator {
            return
        }

        let childContext = isSelf ? (context as! Context<T>) : context.childContext(containerPath: containerPath, elementPath: modelElementPath, childModel: childModel)

        if childContext !== childModel.context {
            value[keyPath: path].withContextAdded(context: childContext, containerPath: \.self, elementPath: \.self, includeSelf: false)
            // For non-self children: set .reference source so they can redirect through context.
            // For self (readModel in Context.init): leave .live source intact so key path access
            // reads directly from Reference._state without going through the context subscript.
            if !isSelf {
                value[keyPath: path].modelContext = ModelContext(context: childContext)
            }
        }
    }

    mutating func visit<T: ModelContainer>(path: WritableKeyPath<Value, T>) {
        if containerPath == \.self, elementPath == \.self {
            value[keyPath: path].withContextAdded(context: context, containerPath: path as! WritableKeyPath<M, T>, elementPath: \.self, includeSelf: false)
        } else {
            value[keyPath: path].withContextAdded(context: context, containerPath: containerPath, elementPath: elementPath.appending(path: path), includeSelf: false)
        }
    }
}
