import IssueReporting

/// Drives `ModelContainer.visit(with:)` implementations, routing each child to the framework's
/// internal model visitor.
///
/// You interact with `ContainerVisitor` inside a `visit(with:)` body — either generated by
/// `@ModelContainer` or written manually. Call `visitDynamically` when the element type is
/// determined at runtime (generic containers), or `visitStatically` when the type is known at
/// compile time (concrete synthesised `visit` bodies):
///
/// ```swift
/// // Generated by @ModelContainer:
/// public func visit(with visitor: inout ContainerVisitor<Self>) {
///     visitor.visitStatically(at: \.loginModel)
///     visitor.visitStatically(at: \.homeModel)
/// }
/// ```
public struct ContainerVisitor<State> {
    var modelVisitor: any ModelVisitor<State>
}

public extension ContainerVisitor {
    /// Visits a child whose concrete type is not known statically.
    ///
    /// Use this in generic `ModelContainer` implementations (such as `Array` or `Dictionary`)
    /// where the element type is a type parameter. The visitor dynamically checks whether the
    /// value is a `Model`, a `ModelContainer`, or a plain value and dispatches accordingly.
    mutating func visitDynamically<T>(with value: T, at path: WritableKeyPath<State, T>) {
        if let model = value as? any Model, !(value is OptionalModel) {
            visit(model: model, path: path)
        } else if let container = value as? any ModelContainer {
            visit(container: container, path: path)
        } else {
            modelVisitor.visit(path: path)
        }
    }
}

public extension ContainerVisitor {
    /// Visits a child at a key path whose type is known at compile time.
    ///
    /// The `@ModelContainer` macro generates calls to this method in synthesised `visit(with:)`
    /// bodies. Prefer `visitDynamically` when the element type is a generic type parameter.
    mutating func visitStatically<T>(at path: WritableKeyPath<State, T>) {
        #if DEBUG
        if let collectionType = T.self as? any _DebugCollectionCheck.Type,
           collectionType._hasModelOrContainerElement() {
            reportIssue("A collection property of \(State.self) contains Model/ModelContainer elements but the collection is not itself a ModelContainer. Make the element type Identifiable so the collection becomes a ModelContainer.")
        }
        #endif
        modelVisitor.visit(path: path)
    }

    mutating func visitStatically<T: Model>(at path: WritableKeyPath<State, T>) {
        modelVisitor.visit(path: path)
    }

    mutating func visitStatically<T: ModelContainer>(at path: WritableKeyPath<State, T>) {
        modelVisitor.visit(path: path)
    }

    mutating func visitStatically<T: ModelContainer&Sequence>(at path: WritableKeyPath<State, T>) {
        modelVisitor.visit(path: path)
    }

    mutating func visitStatically<T: Sequence>(at path: WritableKeyPath<State, T>) where T.Element: Model {
        reportIssue("Collection of models needs to conform to ModelContainer")
        modelVisitor.visit(path: path)
    }

    mutating func visitStatically<T: Sequence>(at path: WritableKeyPath<State, T>) where T.Element: ModelContainer {
        reportIssue("Collection of ModelContainer elements in \(State.self) is not itself a ModelContainer. Make the element type conform to Identifiable (e.g. add `: Identifiable` to the enum and declare `@ModelContainer enum Path: Hashable, Identifiable`).")
        modelVisitor.visit(path: path)
    }

    mutating func visitStatically<M: ModelContainer>(at path: KeyPath<State, M>) {
        reportIssue("Model(Container) of type \(M.self) declared in \(State.self) can't be declared as a let.")
    }

    mutating func visitStatically<T>(at path: KeyPath<State, T>) {
        modelVisitor.visit(path: path)
    }
}

private extension ContainerVisitor {
    mutating func visit<M: Model, T>(model: M, path: WritableKeyPath<State, T>) {
        modelVisitor.visit(path: path as! WritableKeyPath<State, M>)
    }

    mutating func visit<M: ModelContainer, T>(container: M, path: WritableKeyPath<State, T>) {
        modelVisitor.visit(path: path as! WritableKeyPath<State, M>)
    }
}

// MARK: - Debug collection element check

/// A protocol used in `#if DEBUG` builds to detect at the type level whether a collection's
/// element type is a `Model` or `ModelContainer`. This catches cases where a collection holds
/// model children but is not itself a `ModelContainer` — meaning child models would be silently
/// skipped during traversal.
///
/// Explicit conformances are provided for the most common collection types. For any other
/// collection, the compile-time `visitStatically<T: Sequence> where T.Element: ModelContainer`
/// overload serves as the primary safety net.
#if DEBUG
private protocol _DebugCollectionCheck {
    static func _hasModelOrContainerElement() -> Bool
}

private extension Collection {
    static func _hasModelOrContainerElement() -> Bool {
        Element.self is any Model.Type || Element.self is any ModelContainer.Type
    }
}

extension Array: _DebugCollectionCheck {}
extension Set: _DebugCollectionCheck {}
extension ContiguousArray: _DebugCollectionCheck {}
#endif
